import CoreModules.WEASEL.InterfaceDICOMXMLFile
import CoreModules.WEASEL.WriteXMLfromDICOM
import CoreModules.WEASEL.DeveloperTools
import CoreModules.WEASEL.DisplayImageDrawROI
import CoreModules.WEASEL.ImagingTools
from CoreModules.WEASEL.MenuBuilder  import MenuBuilder as menuBuilder