"""
Contains modules that support the display of a series of DICOM images and individual
DICOM images (ImageViewer.py) in an MDI subwindow,
and with the facility to draw an ROI on an image (ImageViewerROI.py)

The folder ComponentsUI contains custom composite widgets used to create the above subwindows.

The folder DataStructures contains the module UserImageColourSelection that 
contains the class UserSelection, which provides the class variables and functions needed
to store and retrieve the data associated with changing the colour table, 
intensity and contrast levels in individual images in a DICOM series of images displayed
on the subwindow generated by ImageViewer.py.
"""
