MAGNIFYING_GLASS_CURSOR = 'FreeHandROI/Icons/Magnifying_Glass.png'
PEN_CURSOR = 'FreeHandROI/Icons/pencil.png'
ERASOR_CURSOR = 'FreeHandROI/Icons/erasor.png'
DELETE_ICON = 'FreeHandROI/Icons/delete_icon.png'
NEW_ICON = 'FreeHandROI/Icons/new_icon.png'
RESET_ICON = 'FreeHandROI/Icons/reset_icon.png'
SAVE_ICON = 'FreeHandROI/Icons/save_icon.png'
LOAD_ICON = 'FreeHandROI/Icons/load_icon.png'
EXPORT_ICON = 'FreeHandROI/Icons/export.png'
CONTRAST_ICON = 'FreeHandROI/Icons/contrast_icon.png'
BRIGHTNESS_ICON = 'FreeHandROI/Icons/brightness_icon.png'
APPLY_SERIES_ICON = 'FreeHandROI/Icons/applySeries_icon.png'

