MAGNIFYING_GLASS_CURSOR = 'CoreModules\\freeHandROI\\Icons\\Magnifying_Glass.png'
PEN_CURSOR = 'CoreModules\\freeHandROI\\Icons\\pencil.png'
ERASOR_CURSOR = 'CoreModules\\freeHandROI\\Icons\\erasor.png'
DELETE_ICON = 'CoreModules\\freeHandROI\\Icons\\delete_icon.png'
NEW_ICON = 'CoreModules\\freeHandROI\\Icons\\new_icon.png'
RESET_ICON = 'CoreModules\\freeHandROI\\Icons\\reset_icon.png'
SAVE_ICON = 'CoreModules\\freeHandROI\\Icons\\save_icon.png'
LOAD_ICON = 'CoreModules\\freeHandROI\\Icons\\load_icon.png'
EXPORT_ICON = 'CoreModules\\freeHandROI\\Icons\\export.png'
CONTRAST_ICON = 'CoreModules\\freeHandROI\\Icons\\contrast_icon.png'
BRIGHTNESS_ICON = 'CoreModules\\freeHandROI\\Icons\\brightness_icon.png'
APPLY_SERIES_ICON = 'CoreModules\\freeHandROI\\Icons\\applySeries_icon.png'

